### ISSUE TITLE
Access-Control-Allow-Origin is invalid when using this in the browser

### ISSUE THREAD

**Issue by et** [Cosmitar/todoist-js#6]
This library works fine on the server but when I try to make the same API requests (e.g. `todoist.sync()`, I get the following error:

```
Failed to load https://todoist.com/API/v7/sync?day_orders_timestamp=&include_notification_settings=1&resource_types=%5B%22all%22%5D&commands=%5B%5D&token=token&sync_token=*: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://localhost:8080' is therefore not allowed access.
```

**Comment by et** [comment]
I guess the requests could just be proxied through a server.
The [example app](https://github.com/fusenlabs/asist) provided though does actually make a direct request so I'm curious how successful that was.

**Comment by Cosmitar** [comment]
Hi @et , never noticed before but you're right, now the request are rejected for CORS. When I developed this API the issue with CORS was only for auth endpoint and had to use a server proxy to achieve it. Now, if all request needs a server proxy, looks like doesn't worth to implement this API on web browsers.
Anyway, Todoist recently released a new REST API, looks more appropriate for web browsers implementations than SYNC API, but I can't tell much more since I didn't try it yet.

**Comment by et** [comment]
Thanks for the fast response @Cosmitar.
It seems advisable to only use a server proxy so people don't accidentally expose their client secret (when doing the initial auth handshake).

Also, is there something with an [`APP_TOKEN`](https://github.com/Cosmitar/todoist-js/blob/5cb37d590a589b577732653b1147eed558a7993c/.env-example#L1) that I'm missing? As far as I know, that's unused.
